Visualizing Access to Health in an LGA in Nigeria
========================================================


```{r}
# setwd("~/Code/Nigeria_Hospital_Access/")
setwd("~/work/r/nigeria_hospital_access/")
require(rgdal)
require(RColorBrewer)
require(raster)
require(maptools)
require(ggplot2)
require(plyr)
require(stringr)
require(rasterVis)
require(rgeos)
require(RSAGA)

nga_pop <- raster('data/nga_pop.tif')
proj <- nga_pop@crs
```
So, we have a gridded population file.

```{r, cache=TRUE, fig.width=7, fig.height=6}
spplot(nga_pop,
       at=c(0, 10, 100, 1000, 10000, 100000),
       col.regions=brewer.pal(6,"Spectral"))

wgs84 <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
nga_shp <- readShapeSpatial("data/nga_states/nga_states.shp", proj4string=wgs84)
nga_states <- spTransform(nga_shp, nga_pop@crs)

cache_or_call <- function(filename, fun) {
  if (file.exists(filename)) {
    readRDS(filename)
  } else {
    tmp <- fun()
    saveRDS(tmp, filename)
    tmp
  }
}
nga_pop_masked <- cache_or_call(
  'data/cache/nga_pop_masked.RDS',
  function () { mask(nga_pop, nga_states) }
  )
```

Step 1: subset by LGA. Lets pick Akwa Ibom.
```{r, cache=TRUE, fig.width=7, fig.height=6}
nga_akwa <- subset(nga_states, Name == "Akwa Ibom")
nga_akwa_raster <- cache_or_call(
  'data/cache/nga_akwa_raster.RDS',
  function() { 
    bb <- nga_akwa@bbox
    e <- extent(bb['x','min'], bb['x', 'max'], bb['y', 'min'], bb['y', 'max'])
    mask(crop(nga_pop, e), nga_akwa)
  })
spplot(nga_akwa_raster,
       at=c(0, 10, 100, 1000, 10000, 100000),
       col.regions=brewer.pal(6,"Spectral"))
```

Step 2: Health Facilities
```{r, cache=TRUE, fig.width=7, fig.height=6}
nga_health <- read.csv("~/Dropbox/Nigeria/Nigeria 661 Baseline Data Cleaning/in_process_data/nmis/data_774/Health_774_NMIS_Facility.csv")
akwa_health <- subset(nga_health, state=="Akwa Ibom")
lat_lng <- colwise(as.numeric)(
  setNames(ldply(str_split(akwa_health$gps, " "),function(x) { x[1:2]}), 
           c("y", "x")))
akwa_health <- SpatialPointsDataFrame(lat_lng, akwa_health)

gplot(nga_akwa_raster) + geom_tile(aes(fill=value)) + scale_fill_continuous(low='white', trans='log10') + geom_point(data=lat_lng, aes(y=y, x=x), color='red', shape='+')
```

Step 3: distance

```{r, cache=TRUE, fig.width=7, fig.height=6}
popAgg <- aggregate(nga_akwa_raster, 2)
popPoints <- as.data.frame(rasterToPoints(popAgg))

ahd <- subset(as.data.frame(akwa_health), select=c("x", "y", "facility_ID"))
ahd$facility_ID <- as.character(ahd$facility_ID)

nearestH <- pick.from.points(popPoints, ahd, radius=2E10)
merged <- merge(nearestH, ahd, by="facility_ID", suffixes=c(".pop", ".health"))
merged$N <- row.names(merged)
mergedPlotDF <- ddply(idata.frame(merged), .(N), function(df) { 
  data.frame(
    x=c(df$x.pop, df$x.health), 
    y=c(df$y.pop, df$y.health),
    group=c(df[1,'N'], df[1,'N']),
    type=c("Population Point", "Health Facility")
)})
gplot(nga_akwa_raster) + geom_tile(aes(fill=value)) + 
  scale_fill_continuous(low="white", trans="log10") + 
  geom_line(data=mergedPlotDF, aes(x=x, y=y, group=group))
```

Step 4:
```{r, cache=TRUE, fig.width=7, fig.height=6}
nga_akwa_buffer <- gBuffer(nga_akwa, width=0.05)
# Getting baseline_data within bbox of buffer

ggplot(data=nga_akwa_buffer, aes(x=long, y=lat, group=group)) + geom_polygon(alpha=0.2) + 
    geom_polygon(data=nga_akwa, aes(x=long, y=lat, group=group)) 

#Getting health facilities over the buffe
lat_lng_akwa <- colwise(as.numeric)(
  setNames(ldply(str_split(nga_health$gps, " "),function(x) { x[1:2]}), 
           c("x", "y")))
# Creating the spatial point df for campare if the points are within the buffer
nga_health_sp <- SpatialPointsDataFrame(lat_lng_akwa, nga_health, proj4string=nga_pop@crs)

#Getting the geo-code of the facilities over the buffer shape
lat_lng_akwa <- lat_lng_akwa[!is.na(over(nga_health_sp, nga_akwa_buffer)),]


nga_lga_shp<- readShapePoly("~/Dropbox/Nigeria/Nigeria 661 Baseline Data Cleaning/raw_data/nga_lgas/nga_lgas_with_corrected_id.shp")

akwa_lga_shp <- subset(nga_lga_shp, STATE == "Akwa Ibom")

akwa_overlay <- function() {
  geom_path(data=akwa_lga_shp, aes(x=long, y=lat, group=group), color='#88888888')
}
blank_theme <- function() {
  theme(axis.text=element_blank(), axis.ticks=element_blank(), 
        panel.grid=element_blank(), axis.title=element_blank())
}

# Plotting
gplot(nga_akwa_raster) + geom_tile(aes(fill=value)) + 
    scale_fill_continuous(low='white', trans='log10', na.value=10^-10) + 
    geom_polygon(data=nga_akwa_buffer, aes(x=long, y=lat), alpha=0.1) + 
    geom_point(data=lat_lng_akwa, aes(x=x, y=y), color="red", shape='+') + 
    akwa_overlay()


```

Step 5: repeat step 3 with buffer data

```{r, cache=TRUE, fig.width=7, fig.height=6}
popAgg <- aggregate(nga_akwa_raster, 2)
popPoints <- as.data.frame(rasterToPoints(popAgg))

ahd <- subset(as.data.frame(nga_health_sp), 
              !is.na(over(nga_health_sp, nga_akwa_buffer)), 
              select=c("x", "y", "facility_ID"))

ahd$facility_ID <- as.character(ahd$facility_ID)

nearestH <- pick.from.points(popPoints, ahd, radius=2E10)
merged <- merge(nearestH, ahd, by="facility_ID", suffixes=c(".pop", ".health"))
merged$N <- row.names(merged)
mergedPlotDF <- ddply(idata.frame(merged), .(N), function(df) { 
  data.frame(
    x=c(df$x.pop, df$x.health), 
    y=c(df$y.pop, df$y.health),
    group=c(df[1,'N'], df[1,'N']),
    Population=c(df[1,'layer'],df[1,'layer']),
    type=c("Population Point", "Health Facility")
)})

mergedPlotDF$Population.Bin <- cut(mergedPlotDF$Population, include.lowest=T,
  breaks=c(1,100,1000,10000,100000),
  labels=c("Below 100", "100-1,000", "1,000-10,000", "> 10,000"))

gplot(nga_akwa_raster) + geom_tile(aes(fill=value)) + 
  scale_fill_continuous(low="white", trans="log10", na.value='#ffffff00') + 
    geom_line(data=mergedPlotDF, 
              aes(x=x, y=y, group=group, color=Population.Bin)) +
    scale_color_brewer(palette="PuRd") + 
    geom_polygon(data=nga_akwa_buffer, aes(x=long, y=lat), alpha=0.1) + 
    geom_point(data=popPoints, aes(x=x, y=y), alpha=0.3) + 
    geom_point(data=lat_lng_akwa, aes(x=x, y=y),
               shape='+', color="black", size=4.5) + 
    blank_theme() + 
    akwa_overlay()


    
```

Pulling the health facility match up result and define the "Best" LGAs

```{r, cache=TRUE, fig.width=7, fig.height=6}
# Loading matching status data from nmis dump
require(RJSONIO)
baseline_status <- fromJSON("~/Dropbox/Nigeria/Nigeria 661 Baseline Data Cleaning/in_process_data/mop_up_matching_result/Matching status/nmis_by_lga.json", simplifyWithNames=T)

baseline_status <- do.call("rbind.fill", lapply(baseline_status, as.data.frame, stringsAsFactors=F))

baseline_status <- subset(baseline_status, select=c("lga_id", "health_total", "health_finished", "health_matched"))
baseline_status <- rename(baseline_status, 
                          c("health_total" = "baseline_total",
                            "health_matched" = "matched",
                            "health_finished" = "baseline_finished"))


facility_status <- fromJSON("~/Dropbox/Nigeria/Nigeria 661 Baseline Data Cleaning/in_process_data/mop_up_matching_result/Matching status/lga_by_lga.json", simplifyWithNames=T)

facility_status <- do.call("rbind.fill", lapply(facility_status, as.data.frame, stringsAsFactors=F))

facility_status <- subset(facility_status, select=c("lga_id", "health_total", "health_finished"))
facility_status <- rename(facility_status, 
                          c("health_total" = "facility_total",
                            "health_finished" = "facility_finished"))


# Load lga info
lgas <- read.csv("~/Dropbox/Nigeria/Nigeria 661 Baseline Data Cleaning/lgas.csv")

edu <- merge(lgas, baseline_status, by="lga_id", all=T)
edu <- merge(edu, facility_status, by="lga_id", all=T)


edu_state <- ddply(edu, .(state), summarize,
             match_count = sum(matched, na.rm=T),
             baseline_total = sum(baseline_total, na.rm=T),
             baseline_finished = sum(baseline_finished, na.rm=T),
             facility_total = sum(facility_total, na.rm=T),
             facility_finished = sum(facility_finished, na.rm=T) 
             )

edu_state$base_facil <- edu_state$baseline_total/edu_state$facility_total
edu_state$match_facil <- edu_state$match_count/edu_state$facility_total
edu_state$facil_complete <- edu_state$facility_finished/edu_state$facility_total
edu_state$base_complete <- edu_state$baseline_finished/edu_state$baseline_total

edu_state$idx <- edu_state$base_facil + edu_state$match_facil + edu_state$facil_complete

edu_state$idx2 <- (0.7*order(edu_state$base_facil, decreasing=F) + 
                   0.5*order(edu_state$match_facil, decreasing=F) -
                    0.2*order(edu_state$match_facil, decreasing=T))

edu_state <- arrange(edu_state, desc(idx2))
```
